MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224_resisc45
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
  # Used to force loss function to torch.nn.CrossEntropyLoss()
  LABEL_SMOOTHING: 0.0
AUG:
  # Used to force loss function to torch.nn.CrossEntropyLoss()
  MIXUP: 0.0
DATA:
  BATCH_SIZE: 4
  DATASET: "resisc45"
  # This is not updating config. Overloading with cmd line args
  CACHE_MODE: 'no'
  ZIP_MODE: True
  PIN_MEMORY: False
  NUM_WORKERS: 1
TRAIN:
  EPOCHS: 25
  BASE_LR: 0.001
  LR_SCHEDULER:
    NAME: 'cosine'
  OPTIMIZER:
    NAME: 'sgd'
TEST:
  SEQUENTIAL: True