OUTPUT: "/afs/ece.cmu.edu/usr/ashwinve/Private/output"
MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224_resisc45
  DROP_PATH_RATE: 0.2
  # Change to pick up from ./data/RESISC45/RESISC45_CLASSES.json dynamically if needed
  NUM_CLASSES: 45
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
    FREEZE_LAYERS: True
    FREEZE_LAYER_INDEX: [0, 1, 2]
  # Used to force loss function to torch.nn.CrossEntropyLoss()
  LABEL_SMOOTHING: 0.0
AUG:
  # Used to force loss function to torch.nn.CrossEntropyLoss()
  MIXUP: 0.0
AMP_ENABLE: False
DATA:
  BATCH_SIZE: 4
  DATASET: "resisc45"
  # This is not updating config. Overloading with cmd line args
  CACHE_MODE: 'no'
  ZIP_MODE: True
  PIN_MEMORY: False
  NUM_WORKERS: 1
TRAIN:
  AUTO_RESUME: False
  USE_CHECKPOINT: True
  # Decide if final MLP is to be thrown away when loading pretrained model
  # Required when starting with ImageNet-1K -> RESISC45 for the first time
  # If loading a checkpoint of RESISC45 model, turn this off
  THROW_MLP_SD: False
  CLIP_GRAD: 1.0
  EPOCHS: 30
  BASE_LR: 1e-3
  WEIGHT_DECAY: 5e-4
  WARMUP_EPOCHS: 3
  WARMUP_LR: 1e-5
  MIN_LR: 5e-6
  LR_SCHEDULER:
    NAME: 'cosine'
  OPTIMIZER:
    NAME: 'sgd'
TEST:
  SEQUENTIAL: True